name = "blue_texas"
authors = ["Jose Daniel Lara <jdlara@berkeley.edu>"]

[deps]
CPLEX = "a076750e-1247-5638-91d2-ce28b192dca0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JavaCall = "494afd89-becb-516b-aafa-70d2670c0337"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PowerSimulations = "e690365d-45e2-57bb-ac84-44ba829e73c4"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
